apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-apps-node-express
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-apps-node-express
  annotations:
    'backstage.io/kubernetes-namespace': my-apps
spec:
  source:
    git:
      ref:
        branch: my-apps
      url: https://github.com/jcospina/node-express.git
